import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NavBar";
import AuthProvider from "./auth/provider";
import { Inter, Roboto } from "next/font/google";
import GoogleScript from "./GoogleScript";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "...",
    description: "...",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleScript />
      <body data-theme="winter" className={roboto.className}>
        <AuthProvider>
          <NavBar />
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
